### PR TITLE
ci: add package building and publishing steps

### PR DESCRIPTION
**Pull request by strk**
Builds packages using linz-software-repository action
Publish packages:
  - to "dev" repository on push to master or packagecloud branches
  - to "test" repository on tag

### CODE REVIEW

**Comment by strk** [comment]
Packaging with linz-software-repository [fails](https://github.com/linz/linz-bde-perl/pull/60/checks?check_run_id=708872510#step:5:286) with:
> Can't locate Test/Exception.pm in @INC

Evidently we're not encoding the dependency on libperl-test-exception in the debian package.
@imincik should we, given it's needed for _testing_ the package ? Or shall we _disable_ testing while building the package, as with instructions in https://github.com/linz/linz-software-repository/wiki/Debian-packaging (`DEB_BUILD_OPTIONS=nocheck`) ? The wiki page does not say WHY would one want to disable checking...

**Comment by strk** [comment]
Adding libtest-exception-perl to debian/control as dependency of source package fixed the problem

**Comment by imincik** [comment]
> The wiki page does not say WHY would one want to disable checking...

I was disabling tests because they need environment like database, most probably accessible without using password. But of course this is doable but I never saw it as priority. So I rather disabled them for now

**Comment by imincik** [comment]
> Adding libtest-exception-perl to debian/control as dependency of source package fixed the problem

ok then. but I think test dependencies should be defined differently - see: https://people.debian.org/~mpitt/autopkgtest/README.package-tests.html . but if  this works then good.

**Pull request merged**
