### PR TITLE
Fix typo in BdeFile::archive_files

### LINKED ISSUE #19: ->archive_files returns list of fields
Writing tests I found that `$bdefile->archive_files` returns all field names, same as `$bdefile->fields`.
I think this is a real bug.

Documentation states:
```
    $bdefile->archive_files(files)
        Retrieve or specify the archive files to include with the data set. If the file is opened
        from a BdeRepository/BdeDataset then this will be automatically populated.
```

In this case the file was *not* opened from a BdeRepository/BdeDataset.

@palmerj should it return 'undef' instead ?

### PR DESCRIPTION
**Pull request by strk**
Closes #19
Enables a test for it

### CODE REVIEW

**Comment by strk** [comment]
There seems to be a race condition in the test. Running `make test` locally uses an increasing amount of RAM until it fails

**Comment by strk** [comment]
A similar self-recursion exists in `sub output_fields` though, so I'm confused

**Comment by palmerj** [comment]
@strk to comment and update PR if required

**Comment by strk** [comment]
Updated:
> t/BdeFile.t ........ 1/? Can't use an undefined value as an ARRAY reference at /home/travis/build/linz/linz-bde-perl/LINZ-Bde-/blib/lib/LINZ/Bde.pm line 198.

**Comment by imincik** [comment]
This task is still relevant.

**Comment by strk** [comment]
How do you like it now, @palmerj ? Travis is happy...

**Pull request merged**
